name: CI

on:
  push: 
    branches:
      - main
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > private_key && chmod 600 private_key
          ssh -tt -o StrictHostKeyChecking=no ${{ secrets.USER_NAME }}@${{ secrets.HOST_NAME }} -i private_key
